name: Build C++ Projects

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build-essential
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config

      - name: Auto-detect required dev packages
        shell: bash
        run: |
          set -eu -o pipefail
          # List of pkg-config libs your projects might need
          LIBS=(gtk+-3.0 vte-2.91 gtksourceview-3.0)
          declare -A PKG_MAP=(
            [gtk+-3.0]=libgtk-3-dev
            [vte-2.91]=libvte-2.91-dev
            [gtksourceview-3.0]=libgtksourceview-3.0-dev
          )
          TO_INSTALL=()
          for lib in "${LIBS[@]}"; do
            if ! pkg-config --exists "$lib"; then
              TO_INSTALL+=("${PKG_MAP[$lib]}")
            fi
          done
          if [ ${#TO_INSTALL[@]} -gt 0 ]; then
            echo "Installing missing packages: ${TO_INSTALL[@]}"
            sudo apt-get install -y "${TO_INSTALL[@]}"
          else
            echo "All required dev packages are already installed."
          fi

      - name: Compile projects with summary
        shell: bash
        run: |
          set -eu -o pipefail
          rm -rf bin
          mkdir -p bin
          SUCCEEDED=()
          FAILED=()
          RED="\033[0;31m"
          GREEN="\033[0;32m"
          YELLOW="\033[0;33m"
          NC="\033[0m"

          while IFS= read -r -d '' dir; do
            dir="${dir#./}"
            [[ "$dir" = ".github" || "$dir" = "bin" || "$dir" = ".git" ]] && continue
            project="$dir"
            echo "=== Processing project: $project ==="

            mapfile -d '' -t CPP_FILES < <(find "$dir" -type f -name '*.cpp' -print0 || true)
            if [ "${#CPP_FILES[@]}" -eq 0 ] && [ ! -f "$dir/Makefile" ]; then
              echo -e "${YELLOW}Skipping $project (no .cpp files or Makefile found)${NC}"
              continue
            fi

            mkdir -p "bin/$project"

            if [ -f "$dir/Makefile" ]; then
              echo "Building $project using Makefile..."
              if make -C "$dir"; then
                find "$dir" -maxdepth 1 -type f -executable -exec mv -t "bin/$project" -- {} + 2>/dev/null || true
                SUCCEEDED+=("$project")
              else
                echo -e "${RED}Make failed for $project${NC}"
                FAILED+=("$project")
              fi
            else
              # Auto-collect include dirs
              readarray -d '' -t HEADER_DIRS < <(find "$dir" -type f \( -name '*.h' -o -name '*.hpp' \) -printf '%h\0' 2>/dev/null | sort -uz || true)
              INCLUDES_ORDER=()

              add_if_missing() {
                local candidate="$1"
                for e in "${INCLUDES_ORDER[@]}"; do [[ "$e" = "$candidate" ]] && return 0; done
                INCLUDES_ORDER+=("$candidate")
              }

              [ -d "$dir/include" ] && add_if_missing "$dir/include"
              [ -d "./include" ] && add_if_missing "$(realpath -m ./include)"
              for hdr in "${HEADER_DIRS[@]}"; do [ -z "$hdr" ] && continue; add_if_missing "$(realpath -m "$hdr")"; done

              INCLUDES_FLAGS=()
              for p in "${INCLUDES_ORDER[@]}"; do INCLUDES_FLAGS+=("-I" "$p"); done

              OUT_BIN="bin/$project/$project"
              echo "Compiling $project from source..."
              if g++ -std=c++17 -Wall "${INCLUDES_FLAGS[@]}" "${CPP_FILES[@]}" -o "$OUT_BIN" $(pkg-config --cflags --libs "${LIBS[@]}"); then
                SUCCEEDED+=("$project")
              else
                echo -e "${RED}g++ failed for $project${NC}"
                FAILED+=("$project")
              fi
            fi
          done < <(find . -maxdepth 1 -mindepth 1 -type d -print0)

          echo
          echo "=== Build Summary ==="
          if [ ${#SUCCEEDED[@]} -gt 0 ]; then
            echo -e "${GREEN}Succeeded projects:${NC} ${SUCCEEDED[*]}"
          else
            echo -e "${YELLOW}No projects succeeded.${NC}"
          fi
          if [ ${#FAILED[@]} -gt 0 ]; then
            echo -e "${RED}Failed projects:${NC} ${FAILED[*]}"
            exit 1
          fi
          echo
          echo "Built projects folder structure:"
          ls -R bin || true

      - name: Upload compiled binaries
        uses: actions/upload-artifact@v4
        with:
          name: compiled-projects-${{ github.run_number }}
          path: bin
          if-no-files-found: error
