name: Build and Bundle C++ Projects

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends build-essential pkg-config libgtk-3-dev libvte-2.91-dev zip

    - name: Compile changed projects
      run: |
        RUN_ID=${GITHUB_RUN_NUMBER}
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        ZIP_NAME="compiled_projects_${TIMESTAMP}_${RUN_ID}.zip"

        mkdir -p bin

        # Only compile directories with changes in src/ or Makefile
        CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'src/|Makefile' | cut -d/ -f1 | sort -u)
        
        for dir in $CHANGED_DIRS; do
          if [ -d "$dir/src" ] || [ -f "$dir/Makefile" ]; then
            project=$(basename $dir)
            mkdir -p bin/$project

            if [ -f "$dir/Makefile" ]; then
              echo "Building $project using its Makefile..."
              make -C $dir
              BIN_NAME=$(basename $(find $dir -maxdepth 1 -type f -executable | head -n1))
              mv $dir/$BIN_NAME bin/$project/
            else
              echo "Building $project with g++..."
              g++ -std=c++17 -Wall $dir/src/*.cpp -o bin/$project/$project $(pkg-config --cflags --libs gtk+-3.0 vte-2.91)
            fi
          fi
        done

        echo "Creating zip $ZIP_NAME..."
        zip -r $ZIP_NAME bin

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-projects-${{ github.run_number }}
        path: compiled_projects_*.zip
        if-no-files-found: error
